---
name: 🐛 Bug Report
description: Report a reproducible bug in the current release of the NetBox Ansible Collection
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        **NOTE:** This form is only for reporting _reproducible bugs_ in a current NetBox Collection
        installation. 
        
        - See the latest ansible module documentation:
          https://netbox-ansible-collection.readthedocs.io
        - Check the release notes:
          https://github.com/netbox-community/ansible_modules/releases
        - Look through the issues already resolved:
          https://github.com/netbox-community/ansible_modules/issues?q=is%3Aclosed
        - Post to Github Discussions if you need setup or usage help that is not a bug:
          https://github.com/netbox-community/ansible_modules/discussions
        - Join the `#ansible` channel on our Slack:
          https://join.slack.com/t/netdev-community/shared_invite/zt-mtts8g0n-Sm6Wutn62q_M4OdsaIycrQ

  - type: input
    attributes:
      label: Ansible NetBox Collection version
      description: What version of the Ansible NetBox Collection are you currently running?
      placeholder: v3.5.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ansible version
      description: >
        What version of the Ansible NetBox Collection are you currently running?
        Paste the output of "ansible --version" 
      value: >
        ```bash

        <!--- Paste verbatim output from "ansible --version" between quotes -->

        ```
    validations:
      required: true
  - type: input
    attributes:
      label: NetBox version
      description: What version of NetBox are you currently running?
      placeholder: v3.1.6
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Python version
      description: What version of Python are you currently running?
      options:
        - "3.8"
        - "3.9"
        - "3.10"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >
        Describe in detail the exact steps that someone else can take to
        reproduce this bug using the current stable release of the Ansible NetBox collection.
        Include any sanatized playbooks, variables, & tasks specifically showing just the issue.
      #placeholder: |

    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A new widget should have been created with the specified attributes
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed Behavior
      description: What happened instead?
      placeholder: A TypeError exception was raised
    validations:
      required: true
